name: "📝 Docs"
description: "문서 작업 요청"
labels: ["documentation"]
body:
  - type: textarea
    attributes:
      label: 📚 문서 설명
      description: 어떤 문서를 작성하거나 수정해야 하는지 설명해주세요.
      placeholder: 예: README 작성, API 명세 추가 등
    validations:
      required: true

  - type: textarea
    attributes:
      label: ✅ 작업할 내용
      description: 필요한 문서 작업을 체크리스트로 작성해주세요.
      placeholder: 구체적인 항목으로 나눠주세요!
    validations:
      required: true

  - type: textarea
    attributes:
      label: 🙋🏻 참고 자료
      description: 관련 링크, 문서 포맷 예시 등이 있다면 적어주세요.
